### ISSUE TITLE
Every login adds an additional 5 analysis.php requests every 5 minutes

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#21]
Seen in Release 1.1.2 and 1.1.3.

![image](https://cloud.githubusercontent.com/assets/24631035/25081645/5e730bd0-2300-11e7-89d0-2e4da1b0e47c.png)

**Comment by nbhasker** [comment]
Fix added in branch NBRapidPolling. Key concept was to unhook the "LogfileCreated" event handler after every use so that multiple instances were not active causing multiple instances of the polling $interval().

**Comment by agvardha** [comment]
Incorporated the fix and verified. It does not put the extra 5 analysis.php. This also was seen as 5 extra log messages In addition to this with low interval timing like 1 min, a 3-4 sequential login-logout corrupted the app. All those have been verified on both ionic serve run and mobile run

**Comment by agvardha** [comment]
I had forgotten to remove the debug code I had added. So there were new issues and log file was all mixed up. Hence I have relabeled them. Currently under smoke test.

**Comment by agvardha** [comment]
Now "LogfileCreated" event handler is totally removed. The reasons for removing LogfileCreated are
1. The parallel operation was being inhibited which is going against the basic design principles
2. The LogfileCreated protected logfile contamination during logging only there was no such protection when using UploadLogFile(). So that was wrong
3. I verified that either while logging or calling UpdateLogFile() no data was lost., It was caught by the preLogin file or the regular one. Some time I can see the DataDownLoad log message getting distributed between 2 log files.
