### ISSUE TITLE
Users are being forced to login after the app has been in the background for a while

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#5]
Users have reported being forced to re-login when they bring the running app from the background to the foreground

**Comment by agvardha** [comment]
This has been fixed and verified on three phones. The fix was mainly in app.js where it senses the app going to pause and resume states. There are tow pause states. One in which the Android OS controls it and the app does not logout. The app is active and all notifications are active. When the app is in the pause state and more apps are pushed to pause state at some point we run out of memory and OS will push CB app out of memory or it gets logged out. This is not a reset just a logut. When we resume now it automatically logs you back. There is some minimal code in login and other controllers.

**Comment by nbhasker** [comment]
Still many opens on code review. Re-opening.

**Comment by nbhasker** [comment]
Simplified fix ready for test on branch NBBackground

**Comment by nbhasker** [comment]
Merged into Ver1p1 today.
