### ISSUE TITLE
Help is displayed within the app and not in a separate browser instance

### ISSUE THREAD

**Issue by nbhasker** [CAGoodman/CareWheelsCorp#60]
This leaves the user with no way to go back to the application and additionally the back button logs out the  user.

**Comment by agvardha** [comment]
With this following tip form Bhasker:
See https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser. I haven't tried it yet.
I had put this note in the Issue description: Looks like we will have to use the Cordova in app browser plugin and then use window.open(url, '_system') or cordova.InAppBrowser.open(url, '_system'). Again hopefully this will work for IOS and Android

We have used window.open(url, '_system')

The problem was fixed for Android.
